plugins {
    id 'fabric-loom' version '1.7.4'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
archivesBaseName = project.archives_base_name

repositories {
    mavenCentral()
    maven { url = "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://maven.blamejared.com" }
    maven { url = uri("file://${projectDir}/libs-repo") }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.minecraft_version}+build.3:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    modCompileOnly "com.terraformersmc:modmenu:11.0.3"
    modImplementation "io.github.kosmx.player-anim:player-animation-lib-fabric:2.0.4+1.21.1"
    modCompileOnly "vazkii.patchouli:Patchouli:1.21.1-92-FABRIC"
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand version: project.version }
}

tasks.withType(JavaCompile).configureEach { options.release = 21; options.encoding = 'UTF-8' }
java { withSourcesJar(); toolchain.languageVersion = JavaLanguageVersion.of(21) }
tasks.withType(Test).configureEach { useJUnitPlatform() }
